function(message_fancy_list list)
  foreach(loop_var ${list})
    message("   • ${loop_var}")
  endforeach(loop_var)
  if(NOT list)
    message("   • <no entities>")
  endif()
endfunction(message_fancy_list)

function(target_link_gtest_and_tested_target TARGET_NAME)
  if ( TARGET_NAME MATCHES "_tests$" )
    message("  Assumed the target is an executable test target (judged from the target name sufix).")
    string(REGEX REPLACE "_tests" "" TESTED_TARGET_NAME "${TARGET_NAME}")
    message("  Assumed tested target: ${TESTED_TARGET_NAME} (judged from the target name prefix).")
    target_link_libraries("${TARGET_NAME}" ${GTEST_LIBRARIES} pthread)
    target_link_libraries("${TARGET_NAME}" "${TESTED_TARGET_NAME}")
  else()
    message(FATAL_ERROR "This CMakeLists.txt should be in the '<terget_name>_tests' directory, where <terget_name> reffers to the terget the tests apply.")
  endif()

endfunction(target_link_gtest_and_tested_target)